/// Configuration options for launching Socure DocV SDK.
///
/// This class contains the required parameters to initialize and launch
/// the document verification flow.
class SocureDocVOptions {
  /// The public SDK key provided by Socure (also called publicKey).
  final String sdkKey;

  /// The transaction token generated by your backend server.
  /// This token is single-use and time-limited for security.
  final String transactionToken;

  /// Optional flag to use Socure Government Cloud (default: false).
  /// Set to true if you're using Socure's government cloud infrastructure.
  final bool useSocureGov;

  const SocureDocVOptions({
    required this.sdkKey,
    required this.transactionToken,
    this.useSocureGov = false,
  });

  /// Converts this options object to a map for method channel communication.
  Map<String, dynamic> toMap() {
    return {
      'sdkKey': sdkKey,
      'transactionToken': transactionToken,
      'useSocureGov': useSocureGov,
    };
  }

  @override
  String toString() {
    return 'SocureDocVOptions(sdkKey: ${sdkKey.substring(0, 8)}..., '
        'transactionToken: ${transactionToken.substring(0, 8)}..., '
        'useSocureGov: $useSocureGov)';
  }
}
