import 'models/socure_docv_options.dart';
import 'models/socure_docv_result.dart';
import 'socure_flutter_platform_interface.dart';

// Export models for easy access
export 'models/socure_docv_error.dart';
export 'models/socure_docv_options.dart';
export 'models/socure_docv_result.dart';

/// Main class for interacting with the Socure DocV SDK.
///
/// This class provides methods to launch document verification flows
/// using the native Socure DocV SDKs on Android and iOS.
///
/// Example usage:
/// ```dart
/// final socure = SocureFlutter();
///
/// // Get transaction token from your backend
/// final token = await getTransactionTokenFromBackend();
///
/// // Configure options
/// final options = SocureDocVOptions(
///   sdkKey: 'your-public-sdk-key',
///   transactionToken: token,
/// );
///
/// // Launch DocV
/// final result = await socure.launchDocV(options);
///
/// // Handle result
/// result.when(
///   success: (data) {
///     print('Session token: ${data.deviceSessionToken}');
///     // Send token to backend for verification
///   },
///   failure: (error) {
///     print('Error: ${error.errorMessage}');
///   },
/// );
/// ```
class SocureFlutter {
  /// Launches the Socure DocV SDK for document verification.
  ///
  /// This method opens the native Socure DocV SDK UI, which guides
  /// the user through document capture and verification.
  ///
  /// Parameters:
  /// - [options]: Configuration options including SDK key and transaction token
  ///
  /// Returns a [SocureDocVResult] which is either:
  /// - [SocureDocVSuccess]: Contains device session token to send to your backend
  /// - [SocureDocVFailure]: Contains error details if verification failed
  ///
  /// The transaction token must be generated by your backend server using
  /// Socure's API before launching the SDK. Each token is single-use and
  /// time-limited for security.
  ///
  /// After receiving a success result, send the device session token to your
  /// backend to fetch the complete verification results using Socure's ID+ API.
  Future<SocureDocVResult> launchDocV(SocureDocVOptions options) {
    return SocureFlutterPlatform.instance.launchDocV(options);
  }

  /// Gets the platform version (for testing purposes).
  ///
  /// Returns a string like "Android 14" or "iOS 17.0".
  Future<String?> getPlatformVersion() {
    return SocureFlutterPlatform.instance.getPlatformVersion();
  }
}
